#!/bin/bash

day=$(date +%e)
case $day in
    1|21|31)
        suffix="st"
        ;;
    2|22)
        suffix="nd"
        ;;
    3|23)
        suffix="rd"
        ;;
    *)
        suffix="th"
        ;;
esac

end=$(date '+%b %Y | %I:%M %p')

echo "$day$suffix of $end"

